//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginwawaky.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencias
    {
        public int idAsistencia { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<System.DateTime> fecha { get; set; } = DateTime.Now;
		public Nullable<bool> estado { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
    }
}
