//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginwawaky.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deberes
    {
        public int idDeber { get; set; }
        public Nullable<int> idMatricula { get; set; }
        public Nullable<int> Parcial { get; set; }
		public int idMateria { get; set; }
		public string NombreDeber { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
    
        public virtual Matriculas Matriculas { get; set; }
		public virtual Materias Materias { get; set; }
	}
}
