//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginwawaky.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materias
    {
        public int idMateria { get; set; }
        public string NombreMateria { get; set; }
        public Nullable<System.DateTime> fechaRegistroM { get; set; }
        public Nullable<bool> estadoM { get; set; }
    }
}
